version: '3.8'

services:
  # --- BASE DE DATOS (MySQL) ---
  mysql-db:
    image: mysql:8.0
    container_name: innovatech-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: InnovatechSecurePassword2026
      MYSQL_DATABASE: innovatech_db
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: InnovatechSecurePassword2026
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - innovatech-net

  # --- MICROSERVICIO: DESPACHOS ---
  back-despachos:
    image: 176901090381.dkr.ecr.us-east-1.amazonaws.com/innovatech-back-despachos:latest
    build:
      context: "./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO" 
      dockerfile: Dockerfile
    container_name: back-despachos
    restart: always
    ports:
      - "8081:8081" # Corregido: mapeo puerto 8081 interno (definido en properties)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/innovatech_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USERNAME=devops_user
      - DB_PASSWORD=InnovatechSecurePassword2026
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      - mysql-db
    networks:
      - innovatech-net

  # --- MICROSERVICIO: VENTAS ---
  back-ventas:
    image: 176901090381.dkr.ecr.us-east-1.amazonaws.com/innovatech-back-ventas:latest
    build:
      context: "./back-Ventas_SpringBoot/Springboot-API-REST" 
      dockerfile: Dockerfile
    container_name: back-ventas
    restart: always
    ports:
      - "8082:8080" # Ajustado para consistencia
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/innovatech_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USERNAME=devops_user
      - DB_PASSWORD=InnovatechSecurePassword2026
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      - mysql-db
    networks:
      - innovatech-net

networks:
  innovatech-net:
    driver: bridge

volumes:
  mysql_data:
