server {
    listen 8080;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # 1. Rutas de React (Evita el error 404 al recargar la página)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Puente directo a tu microservicio de Despachos en la EC2-Backend
    location /despachos {
        proxy_pass http://10.0.143.60:8080/despachos; 
    }

    # 3. (Opcional) Puente a Ventas, por si tu Frontend también lo consume
    location /ventas {
        proxy_pass http://10.0.143.60:8081/ventas; 
    }
}